
<Structures>
  <Structure Name="Entity" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000000" Description="tagID" DisplayMethod="hexadecimal"/>
      <Element Offset="2" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000002" DisplayMethod="hexadecimal"/>
      <Element Offset="4" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000004" DisplayMethod="unsigned integer"/>
      <Element Offset="16" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000010" DisplayMethod="hexadecimal"/>
      <Element Offset="20" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000014" Description="ageMilis" DisplayMethod="unsigned integer"/>
      <Element Offset="24" Vartype="Float" Bytesize="4" OffsetHex="00000018" Description="pos.x" DisplayMethod="unsigned integer"/>
      <Element Offset="28" Vartype="Float" Bytesize="4" OffsetHex="0000001C" Description="pos.y" DisplayMethod="unsigned integer"/>
      <Element Offset="32" Vartype="Float" Bytesize="4" OffsetHex="00000020" Description="pos.z" DisplayMethod="unsigned integer"/>
      <Element Offset="36" Vartype="Float" Bytesize="4" OffsetHex="00000024" Description="vel.x" DisplayMethod="unsigned integer"/>
      <Element Offset="40" Vartype="Float" Bytesize="4" OffsetHex="00000028" Description="vel.y" DisplayMethod="unsigned integer"/>
      <Element Offset="44" Vartype="Float" Bytesize="4" OffsetHex="0000002C" Description="vel.z" DisplayMethod="unsigned integer"/>
      <Element Offset="48" Vartype="Float" Bytesize="4" OffsetHex="00000030" Description="fwd.x" DisplayMethod="unsigned integer"/>
      <Element Offset="52" Vartype="Float" Bytesize="4" OffsetHex="00000034" Description="fwd.y" DisplayMethod="unsigned integer"/>
      <Element Offset="56" Vartype="Float" Bytesize="4" OffsetHex="00000038" Description="fwd.z" DisplayMethod="unsigned integer"/>
      <Element Offset="60" Vartype="Float" Bytesize="4" OffsetHex="0000003C" Description="up.x" DisplayMethod="unsigned integer"/>
      <Element Offset="64" Vartype="Float" Bytesize="4" OffsetHex="00000040" Description="up.y" DisplayMethod="unsigned integer"/>
      <Element Offset="68" Vartype="Float" Bytesize="4" OffsetHex="00000044" Description="up.z" DisplayMethod="unsigned integer"/>
      <Element Offset="72" Vartype="Float" Bytesize="4" OffsetHex="00000048" Description="angularVel.x" DisplayMethod="unsigned integer"/>
      <Element Offset="76" Vartype="Float" Bytesize="4" OffsetHex="0000004C" Description="angularVel.y" DisplayMethod="unsigned integer"/>
      <Element Offset="80" Vartype="Float" Bytesize="4" OffsetHex="00000050" Description="angularVel.z" DisplayMethod="unsigned integer"/>
      <Element Offset="84" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000054" DisplayMethod="unsigned integer"/>
      <Element Offset="92" Vartype="Float" Bytesize="4" OffsetHex="0000005C" Description="rootBone.x" DisplayMethod="unsigned integer"/>
      <Element Offset="96" Vartype="Float" Bytesize="4" OffsetHex="00000060" Description="rootBone.y" DisplayMethod="unsigned integer"/>
      <Element Offset="100" Vartype="Float" Bytesize="4" OffsetHex="00000064" Description="rootBone.z" DisplayMethod="unsigned integer"/>
      <Element Offset="104" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000068" DisplayMethod="unsigned integer"/>
      <Element Offset="112" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000070" Description="entityCategory" DisplayMethod="unsigned integer"/>
      <Element Offset="116" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000074" DisplayMethod="hexadecimal"/>
      <Element Offset="120" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000078" DisplayMethod="unsigned integer"/>
      <Element Offset="124" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000007C" DisplayMethod="hexadecimal"/>
      <Element Offset="128" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000080" Description="controllerHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="132" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000084" DisplayMethod="unsigned integer"/>
      <Element Offset="136" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000088" DisplayMethod="hexadecimal"/>
      <Element Offset="140" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000008C" Description="animID" DisplayMethod="hexadecimal"/>
      <Element Offset="142" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000008E" Description="animFrame" DisplayMethod="unsigned integer"/>
      <Element Offset="144" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000090" DisplayMethod="unsigned integer"/>
      <Element Offset="148" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000094" DisplayMethod="unsigned integer"/>
      <Element Offset="156" Vartype="Float" Bytesize="4" OffsetHex="0000009C" Description="health" DisplayMethod="unsigned integer"/>
      <Element Offset="160" Vartype="Float" Bytesize="4" OffsetHex="000000A0" Description="shield" DisplayMethod="unsigned integer"/>
      <Element Offset="164" Vartype="4 Bytes" Bytesize="4" RLECount="9" OffsetHex="000000A4" DisplayMethod="unsigned integer"/>
      <Element Offset="200" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000C8" DisplayMethod="hexadecimal"/>
      <Element Offset="204" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000CC" DisplayMethod="unsigned integer"/>
      <Element Offset="208" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000D0" Description="vehicleHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="212" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000D4" Description="childHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="216" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000D8" Description="parentHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="220" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000DC" DisplayMethod="hexadecimal"/>
      <Element Offset="224" Vartype="Double" Bytesize="8" OffsetHex="000000E0" DisplayMethod="unsigned integer"/>
      <Element Offset="232" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="000000E8" DisplayMethod="unsigned integer"/>
      <Element Offset="264" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000108" DisplayMethod="hexadecimal"/>
      <Element Offset="268" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="0000010C" DisplayMethod="unsigned integer"/>
      <Element Offset="300" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000012C" DisplayMethod="hexadecimal"/>
      <Element Offset="304" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000130" DisplayMethod="unsigned integer"/>
      <Element Offset="320" Vartype="Double" Bytesize="8" OffsetHex="00000140" DisplayMethod="unsigned integer"/>
      <Element Offset="328" Vartype="Float" Bytesize="4" RLECount="11" OffsetHex="00000148" DisplayMethod="unsigned integer"/>
      <Element Offset="372" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000174" DisplayMethod="unsigned integer"/>
      <Element Offset="380" Vartype="Double" Bytesize="8" OffsetHex="0000017C" DisplayMethod="unsigned integer"/>
      <Element Offset="388" Vartype="Float" Bytesize="4" RLECount="8" OffsetHex="00000184" DisplayMethod="unsigned integer"/>
      <Element Offset="420" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="000001A4" DisplayMethod="hexadecimal"/>
      <Element Offset="440" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="000001B8" DisplayMethod="unsigned integer"/>
      <Element Offset="460" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001CC" Description="previousWeaponOwnerHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="464" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001D0" DisplayMethod="unsigned integer"/>
      <Element Offset="468" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001D4" DisplayMethod="hexadecimal"/>
      <Element Offset="472" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001D8" DisplayMethod="unsigned integer"/>
      <Element Offset="476" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001DC" DisplayMethod="hexadecimal"/>
      <Element Offset="480" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000001E0" DisplayMethod="unsigned integer"/>
      <Element Offset="504" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000001F8" DisplayMethod="hexadecimal"/>
      <Element Offset="512" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000200" Description="projectileParentHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="516" Vartype="Float" Bytesize="4" OffsetHex="00000204" Description="heat" DisplayMethod="unsigned integer"/>
      <Element Offset="520" Vartype="Float" Bytesize="4" OffsetHex="00000208" Description="plasmaUsed" DisplayMethod="unsigned integer"/>
      <Element Offset="524" Vartype="Float" Bytesize="4" OffsetHex="0000020C" Description="fuse" DisplayMethod="unsigned integer"/>
      <Element Offset="528" Vartype="Float" Bytesize="4" OffsetHex="00000210" Description="look.x" DisplayMethod="unsigned integer"/>
      <Element Offset="532" Vartype="Float" Bytesize="4" OffsetHex="00000214" Description="look.y" DisplayMethod="unsigned integer"/>
      <Element Offset="536" Vartype="Float" Bytesize="4" OffsetHex="00000218" Description="look.z" DisplayMethod="unsigned integer"/>
      <Element Offset="540" Vartype="Float" Bytesize="4" OffsetHex="0000021C" Description="projectileAge" DisplayMethod="unsigned integer"/>
      <Element Offset="544" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000220" DisplayMethod="unsigned integer"/>
      <Element Offset="552" Vartype="Byte" Bytesize="1" OffsetHex="00000228" Description="ticksSinceLastFired" DisplayMethod="unsigned integer"/>
      <Element Offset="553" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000229" DisplayMethod="unsigned integer"/>
      <Element Offset="556" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000022C" DisplayMethod="unsigned integer"/>
      <Element Offset="560" Vartype="Double" Bytesize="8" OffsetHex="00000230" DisplayMethod="unsigned integer"/>
      <Element Offset="568" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000238" DisplayMethod="unsigned integer"/>
      <Element Offset="576" Vartype="Float" Bytesize="4" OffsetHex="00000240" Description="plasmaCharge" DisplayMethod="unsigned integer"/>
      <Element Offset="580" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000244" DisplayMethod="unsigned integer"/>
      <Element Offset="588" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="0000024C" DisplayMethod="unsigned integer"/>
      <Element Offset="620" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000026C" DisplayMethod="hexadecimal"/>
      <Element Offset="624" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000270" DisplayMethod="unsigned integer"/>
      <Element Offset="632" Vartype="Byte" Bytesize="1" RLECount="9" OffsetHex="00000278" DisplayMethod="hexadecimal"/>
      <Element Offset="641" Vartype="Byte" Bytesize="1" OffsetHex="00000281" Description="weaponIndex" DisplayMethod="hexadecimal"/>
      <Element Offset="642" Vartype="Byte" Bytesize="1" OffsetHex="00000282" DisplayMethod="hexadecimal"/>
      <Element Offset="643" Vartype="Byte" Bytesize="1" OffsetHex="00000283" Description="grenadeAnim" DisplayMethod="hexadecimal"/>
      <Element Offset="644" Vartype="Byte" Bytesize="1" OffsetHex="00000284" Description="weaponAnim" DisplayMethod="hexadecimal"/>
      <Element Offset="645" Vartype="Byte" Bytesize="1" OffsetHex="00000285" DisplayMethod="hexadecimal"/>
      <Element Offset="646" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000286" Description="ammo" DisplayMethod="unsigned integer"/>
      <Element Offset="648" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000288" DisplayMethod="hexadecimal"/>
      <Element Offset="650" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000028A" Description="clipAmmo" DisplayMethod="unsigned integer"/>
      <Element Offset="652" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="0000028C" DisplayMethod="hexadecimal"/>
      <Element Offset="660" Vartype="Double" Bytesize="8" OffsetHex="00000294" DisplayMethod="unsigned integer"/>
      <Element Offset="668" Vartype="Float" Bytesize="4" RLECount="7" OffsetHex="0000029C" DisplayMethod="unsigned integer"/>
      <Element Offset="696" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000002B8" DisplayMethod="unsigned integer"/>
      <Element Offset="704" Vartype="Float" Bytesize="4" OffsetHex="000002C0" DisplayMethod="unsigned integer"/>
      <Element Offset="708" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000002C4" DisplayMethod="unsigned integer"/>
      <Element Offset="720" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002D0" DisplayMethod="hexadecimal"/>
      <Element Offset="724" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002D4" DisplayMethod="unsigned integer"/>
      <Element Offset="728" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000002D8" DisplayMethod="hexadecimal"/>
      <Element Offset="736" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="000002E0" DisplayMethod="unsigned integer"/>
      <Element Offset="764" Vartype="Byte" Bytesize="1" OffsetHex="000002FC" Description="frags" DisplayMethod="unsigned integer"/>
      <Element Offset="765" Vartype="Byte" Bytesize="1" OffsetHex="000002FD" Description="plasmas" DisplayMethod="unsigned integer"/>
      <Element Offset="766" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="000002FE" DisplayMethod="hexadecimal"/>
      <Element Offset="768" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000300" DisplayMethod="hexadecimal"/>
      <Element Offset="772" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000304" Description="vehicleRiderHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="776" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000308" Description="vehicleRiderHandle2" DisplayMethod="hexadecimal"/>
      <Element Offset="780" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000030C" DisplayMethod="unsigned integer"/>
      <Element Offset="784" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000310" DisplayMethod="hexadecimal"/>
      <Element Offset="788" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000314" DisplayMethod="unsigned integer"/>
      <Element Offset="804" Vartype="Double" Bytesize="8" OffsetHex="00000324" DisplayMethod="unsigned integer"/>
      <Element Offset="812" Vartype="4 Bytes" Bytesize="4" RLECount="15" OffsetHex="0000032C" DisplayMethod="unsigned integer"/>
      <Element Offset="872" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000368" DisplayMethod="hexadecimal"/>
      <Element Offset="876" Vartype="4 Bytes" Bytesize="4" RLECount="40" OffsetHex="0000036C" DisplayMethod="unsigned integer"/>
      <Element Offset="1036" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000040C" DisplayMethod="hexadecimal"/>
      <Element Offset="1040" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000410" DisplayMethod="unsigned integer"/>
      <Element Offset="1048" Vartype="Float" Bytesize="4" OffsetHex="00000418" DisplayMethod="unsigned integer"/>
      <Element Offset="1052" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="0000041C" DisplayMethod="hexadecimal"/>
      <Element Offset="1060" Vartype="4 Bytes" Bytesize="4" RLECount="42" OffsetHex="00000424" DisplayMethod="unsigned integer"/>
      <Element Offset="1228" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000004CC" DisplayMethod="hexadecimal"/>
      <Element Offset="1236" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000004D4" DisplayMethod="unsigned integer"/>
      <Element Offset="1260" Vartype="Float" Bytesize="4" RLECount="3" OffsetHex="000004EC" DisplayMethod="unsigned integer"/>
      <Element Offset="1272" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="000004F8" DisplayMethod="unsigned integer"/>
      <Element Offset="1288" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000508" DisplayMethod="hexadecimal"/>
      <Element Offset="1292" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="0000050C" DisplayMethod="unsigned integer"/>
      <Element Offset="1312" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000520" DisplayMethod="unsigned integer"/>
      <Element Offset="1320" Vartype="Byte" Bytesize="1" OffsetHex="00000528" DisplayMethod="unsigned integer"/>
      <Element Offset="1321" Vartype="String" Bytesize="4" OffsetHex="00000529" DisplayMethod="unsigned integer"/>
      <Element Offset="1325" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="0000052D" DisplayMethod="unsigned integer"/>
      <Element Offset="1328" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000530" DisplayMethod="hexadecimal"/>
      <Element Offset="1332" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000534" DisplayMethod="unsigned integer"/>
      <Element Offset="1348" Vartype="Double" Bytesize="8" OffsetHex="00000544" DisplayMethod="unsigned integer"/>
      <Element Offset="1356" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000054C" DisplayMethod="unsigned integer"/>
      <Element Offset="1360" Vartype="Double" Bytesize="8" OffsetHex="00000550" DisplayMethod="unsigned integer"/>
      <Element Offset="1368" Vartype="Byte" Bytesize="1" OffsetHex="00000558" DisplayMethod="unsigned integer"/>
      <Element Offset="1369" Vartype="String" Bytesize="4" OffsetHex="00000559" DisplayMethod="unsigned integer"/>
      <Element Offset="1373" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="0000055D" DisplayMethod="unsigned integer"/>
      <Element Offset="1376" Vartype="Double" Bytesize="8" OffsetHex="00000560" DisplayMethod="unsigned integer"/>
      <Element Offset="1384" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000568" DisplayMethod="unsigned integer"/>
      <Element Offset="1388" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000056C" DisplayMethod="unsigned integer"/>
      <Element Offset="1392" Vartype="Float" Bytesize="4" RLECount="4" OffsetHex="00000570" DisplayMethod="unsigned integer"/>
      <Element Offset="1408" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000580" DisplayMethod="unsigned integer"/>
      <Element Offset="1411" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000583" DisplayMethod="unsigned integer"/>
      <Element Offset="1413" Vartype="Byte" Bytesize="1" OffsetHex="00000585" DisplayMethod="unsigned integer"/>
      <Element Offset="1414" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000586" DisplayMethod="unsigned integer"/>
      <Element Offset="1416" Vartype="Float" Bytesize="4" RLECount="18" OffsetHex="00000588" DisplayMethod="unsigned integer"/>
      <Element Offset="1488" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="000005D0" DisplayMethod="unsigned integer"/>
      <Element Offset="1492" Vartype="Float" Bytesize="4" RLECount="31" OffsetHex="000005D4" DisplayMethod="unsigned integer"/>
      <Element Offset="1616" Vartype="String" Bytesize="4" OffsetHex="00000650" DisplayMethod="unsigned integer"/>
      <Element Offset="1620" Vartype="Float" Bytesize="4" RLECount="6" OffsetHex="00000654" DisplayMethod="unsigned integer"/>
      <Element Offset="1644" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="0000066C" DisplayMethod="unsigned integer"/>
      <Element Offset="1648" Vartype="Float" Bytesize="4" RLECount="18" OffsetHex="00000670" DisplayMethod="unsigned integer"/>
      <Element Offset="1720" Vartype="String" Bytesize="4" OffsetHex="000006B8" DisplayMethod="unsigned integer"/>
      <Element Offset="1724" Vartype="Float" Bytesize="4" RLECount="20" OffsetHex="000006BC" DisplayMethod="unsigned integer"/>
      <Element Offset="1804" Vartype="Byte" Bytesize="1" OffsetHex="0000070C" DisplayMethod="unsigned integer"/>
      <Element Offset="1805" Vartype="String" Bytesize="5" OffsetHex="0000070D" DisplayMethod="unsigned integer"/>
      <Element Offset="1810" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000712" DisplayMethod="unsigned integer"/>
      <Element Offset="1812" Vartype="Float" Bytesize="4" RLECount="36" OffsetHex="00000714" DisplayMethod="unsigned integer"/>
      <Element Offset="1956" Vartype="String" Bytesize="5" OffsetHex="000007A4" DisplayMethod="unsigned integer"/>
      <Element Offset="1961" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="000007A9" DisplayMethod="unsigned integer"/>
      <Element Offset="1964" Vartype="Float" Bytesize="4" RLECount="25" OffsetHex="000007AC" DisplayMethod="unsigned integer"/>
      <Element Offset="2064" Vartype="String" Bytesize="5" OffsetHex="00000810" DisplayMethod="unsigned integer"/>
      <Element Offset="2069" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000815" DisplayMethod="unsigned integer"/>
      <Element Offset="2072" Vartype="Float" Bytesize="4" RLECount="18" OffsetHex="00000818" DisplayMethod="unsigned integer"/>
      <Element Offset="2144" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000860" DisplayMethod="unsigned integer"/>
      <Element Offset="2148" Vartype="Float" Bytesize="4" RLECount="10" OffsetHex="00000864" DisplayMethod="unsigned integer"/>
      <Element Offset="2188" Vartype="String" Bytesize="5" OffsetHex="0000088C" DisplayMethod="unsigned integer"/>
      <Element Offset="2193" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000891" DisplayMethod="unsigned integer"/>
      <Element Offset="2196" Vartype="Float" Bytesize="4" RLECount="27" OffsetHex="00000894" DisplayMethod="unsigned integer"/>
      <Element Offset="2304" Vartype="Double" Bytesize="8" OffsetHex="00000900" DisplayMethod="unsigned integer"/>
      <Element Offset="2312" Vartype="Float" Bytesize="4" RLECount="11" OffsetHex="00000908" DisplayMethod="unsigned integer"/>
      <Element Offset="2356" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000934" DisplayMethod="unsigned integer"/>
      <Element Offset="2364" Vartype="Float" Bytesize="4" RLECount="6" OffsetHex="0000093C" DisplayMethod="unsigned integer"/>
      <Element Offset="2388" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000954" DisplayMethod="hexadecimal"/>
      <Element Offset="2396" Vartype="Float" Bytesize="4" RLECount="5" OffsetHex="0000095C" DisplayMethod="unsigned integer"/>
      <Element Offset="2416" Vartype="Byte" Bytesize="1" OffsetHex="00000970" DisplayMethod="unsigned integer"/>
      <Element Offset="2417" Vartype="String" Bytesize="4" OffsetHex="00000971" DisplayMethod="unsigned integer"/>
      <Element Offset="2421" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000975" DisplayMethod="unsigned integer"/>
      <Element Offset="2424" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000978" DisplayMethod="hexadecimal"/>
      <Element Offset="2428" Vartype="Float" Bytesize="4" RLECount="5" OffsetHex="0000097C" DisplayMethod="unsigned integer"/>
      <Element Offset="2448" Vartype="String" Bytesize="4" OffsetHex="00000990" DisplayMethod="unsigned integer"/>
      <Element Offset="2452" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000994" DisplayMethod="unsigned integer"/>
      <Element Offset="2460" Vartype="String" Bytesize="5" OffsetHex="0000099C" DisplayMethod="unsigned integer"/>
      <Element Offset="2465" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="000009A1" DisplayMethod="unsigned integer"/>
      <Element Offset="2468" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000009A4" DisplayMethod="unsigned integer"/>
      <Element Offset="2476" Vartype="Double" Bytesize="8" OffsetHex="000009AC" DisplayMethod="unsigned integer"/>
      <Element Offset="2484" Vartype="Byte" Bytesize="1" OffsetHex="000009B4" DisplayMethod="unsigned integer"/>
      <Element Offset="2485" Vartype="String" Bytesize="4" OffsetHex="000009B5" DisplayMethod="unsigned integer"/>
      <Element Offset="2489" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="000009B9" DisplayMethod="unsigned integer"/>
      <Element Offset="2492" Vartype="Double" Bytesize="8" OffsetHex="000009BC" DisplayMethod="unsigned integer"/>
      <Element Offset="2500" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000009C4" DisplayMethod="unsigned integer"/>
      <Element Offset="2508" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="000009CC" DisplayMethod="unsigned integer"/>
      <Element Offset="2516" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="000009D4" DisplayMethod="unsigned integer"/>
      <Element Offset="2518" Vartype="2 Bytes" Bytesize="2" OffsetHex="000009D6" DisplayMethod="unsigned integer"/>
      <Element Offset="2520" Vartype="4 Bytes" Bytesize="4" OffsetHex="000009D8" DisplayMethod="hexadecimal"/>
      <Element Offset="2524" Vartype="Float" Bytesize="4" RLECount="5" OffsetHex="000009DC" DisplayMethod="unsigned integer"/>
      <Element Offset="2544" Vartype="Byte" Bytesize="1" OffsetHex="000009F0" DisplayMethod="unsigned integer"/>
      <Element Offset="2545" Vartype="String" Bytesize="4" OffsetHex="000009F1" DisplayMethod="unsigned integer"/>
      <Element Offset="2549" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="000009F5" DisplayMethod="unsigned integer"/>
      <Element Offset="2552" Vartype="Float" Bytesize="4" OffsetHex="000009F8" DisplayMethod="unsigned integer"/>
      <Element Offset="2556" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="000009FC" DisplayMethod="unsigned integer"/>
      <Element Offset="2558" Vartype="2 Bytes" Bytesize="2" OffsetHex="000009FE" DisplayMethod="unsigned integer"/>
      <Element Offset="2560" Vartype="Float" Bytesize="4" RLECount="14" OffsetHex="00000A00" DisplayMethod="unsigned integer"/>
      <Element Offset="2616" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000A38" DisplayMethod="hexadecimal"/>
      <Element Offset="2620" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000A3C" DisplayMethod="unsigned integer"/>
      <Element Offset="2628" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000A44" DisplayMethod="unsigned integer"/>
      <Element Offset="2636" Vartype="Float" Bytesize="4" RLECount="4" OffsetHex="00000A4C" DisplayMethod="unsigned integer"/>
      <Element Offset="2652" Vartype="Double" Bytesize="8" OffsetHex="00000A5C" DisplayMethod="unsigned integer"/>
      <Element Offset="2660" Vartype="Float" Bytesize="4" RLECount="13" OffsetHex="00000A64" DisplayMethod="unsigned integer"/>
      <Element Offset="2712" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000A98" DisplayMethod="unsigned integer"/>
      <Element Offset="2716" Vartype="Double" Bytesize="8" OffsetHex="00000A9C" DisplayMethod="unsigned integer"/>
      <Element Offset="2724" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000AA4" DisplayMethod="unsigned integer"/>
      <Element Offset="2732" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="00000AAC" DisplayMethod="unsigned integer"/>
      <Element Offset="2734" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000AAE" DisplayMethod="unsigned integer"/>
      <Element Offset="2736" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000AB0" DisplayMethod="unsigned integer"/>
      <Element Offset="2744" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000AB8" DisplayMethod="hexadecimal"/>
      <Element Offset="2748" Vartype="Float" Bytesize="4" RLECount="7" OffsetHex="00000ABC" DisplayMethod="unsigned integer"/>
      <Element Offset="2776" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000AD8" DisplayMethod="hexadecimal"/>
      <Element Offset="2780" Vartype="Double" Bytesize="8" OffsetHex="00000ADC" DisplayMethod="unsigned integer"/>
      <Element Offset="2788" Vartype="Float" Bytesize="4" OffsetHex="00000AE4" DisplayMethod="unsigned integer"/>
      <Element Offset="2792" Vartype="String" Bytesize="4" OffsetHex="00000AE8" DisplayMethod="unsigned integer"/>
      <Element Offset="2796" Vartype="Float" Bytesize="4" RLECount="3" OffsetHex="00000AEC" DisplayMethod="unsigned integer"/>
      <Element Offset="2808" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000AF8" DisplayMethod="hexadecimal"/>
      <Element Offset="2812" Vartype="Double" Bytesize="8" OffsetHex="00000AFC" DisplayMethod="unsigned integer"/>
      <Element Offset="2820" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B04" DisplayMethod="unsigned integer"/>
      <Element Offset="2824" Vartype="Double" Bytesize="8" OffsetHex="00000B08" DisplayMethod="unsigned integer"/>
      <Element Offset="2832" Vartype="String" Bytesize="6" OffsetHex="00000B10" DisplayMethod="unsigned integer"/>
      <Element Offset="2838" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="00000B16" DisplayMethod="unsigned integer"/>
      <Element Offset="2840" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B18" DisplayMethod="unsigned integer"/>
      <Element Offset="2844" Vartype="Double" Bytesize="8" OffsetHex="00000B1C" DisplayMethod="unsigned integer"/>
      <Element Offset="2852" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B24" DisplayMethod="unsigned integer"/>
      <Element Offset="2856" Vartype="Double" Bytesize="8" OffsetHex="00000B28" DisplayMethod="unsigned integer"/>
      <Element Offset="2864" Vartype="Byte" Bytesize="1" OffsetHex="00000B30" DisplayMethod="unsigned integer"/>
      <Element Offset="2865" Vartype="String" Bytesize="5" OffsetHex="00000B31" DisplayMethod="unsigned integer"/>
      <Element Offset="2870" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="00000B36" DisplayMethod="unsigned integer"/>
      <Element Offset="2872" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B38" DisplayMethod="unsigned integer"/>
      <Element Offset="2876" Vartype="Double" Bytesize="8" OffsetHex="00000B3C" DisplayMethod="unsigned integer"/>
      <Element Offset="2884" Vartype="String" Bytesize="4" OffsetHex="00000B44" DisplayMethod="unsigned integer"/>
      <Element Offset="2888" Vartype="Float" Bytesize="4" RLECount="4" OffsetHex="00000B48" DisplayMethod="unsigned integer"/>
      <Element Offset="2904" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B58" DisplayMethod="hexadecimal"/>
      <Element Offset="2908" Vartype="Double" Bytesize="8" OffsetHex="00000B5C" DisplayMethod="unsigned integer"/>
      <Element Offset="2916" Vartype="Float" Bytesize="4" RLECount="5" OffsetHex="00000B64" DisplayMethod="unsigned integer"/>
      <Element Offset="2936" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B78" DisplayMethod="hexadecimal"/>
      <Element Offset="2940" Vartype="Float" Bytesize="4" RLECount="14" OffsetHex="00000B7C" DisplayMethod="unsigned integer"/>
      <Element Offset="2996" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000BB4" DisplayMethod="hexadecimal"/>
      <Element Offset="3004" Vartype="Float" Bytesize="4" RLECount="6" OffsetHex="00000BBC" DisplayMethod="unsigned integer"/>
      <Element Offset="3028" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000BD4" DisplayMethod="hexadecimal"/>
      <Element Offset="3036" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000BDC" DisplayMethod="unsigned integer"/>
      <Element Offset="3044" Vartype="Byte" Bytesize="1" OffsetHex="00000BE4" DisplayMethod="unsigned integer"/>
      <Element Offset="3045" Vartype="String" Bytesize="6" OffsetHex="00000BE5" DisplayMethod="unsigned integer"/>
      <Element Offset="3051" Vartype="Byte" Bytesize="1" OffsetHex="00000BEB" DisplayMethod="unsigned integer"/>
      <Element Offset="3052" Vartype="Float" Bytesize="4" RLECount="6" OffsetHex="00000BEC" DisplayMethod="unsigned integer"/>
      <Element Offset="3076" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000C04" DisplayMethod="unsigned integer"/>
      <Element Offset="3080" Vartype="Double" Bytesize="8" OffsetHex="00000C08" DisplayMethod="unsigned integer"/>
      <Element Offset="3088" Vartype="Float" Bytesize="4" OffsetHex="00000C10" DisplayMethod="unsigned integer"/>
      <Element Offset="3092" Vartype="Byte" Bytesize="1" OffsetHex="00000C14" DisplayMethod="unsigned integer"/>
      <Element Offset="3093" Vartype="String" Bytesize="4" OffsetHex="00000C15" DisplayMethod="unsigned integer"/>
      <Element Offset="3097" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000C19" DisplayMethod="unsigned integer"/>
      <Element Offset="3100" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000C1C" DisplayMethod="unsigned integer"/>
      <Element Offset="3108" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000C24" DisplayMethod="unsigned integer"/>
      <Element Offset="3116" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000C2C" DisplayMethod="unsigned integer"/>
      <Element Offset="3124" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="00000C34" DisplayMethod="unsigned integer"/>
      <Element Offset="3126" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000C36" DisplayMethod="unsigned integer"/>
      <Element Offset="3128" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000C38" DisplayMethod="unsigned integer"/>
      <Element Offset="3132" Vartype="Double" Bytesize="8" OffsetHex="00000C3C" DisplayMethod="unsigned integer"/>
      <Element Offset="3140" Vartype="Float" Bytesize="4" RLECount="6" OffsetHex="00000C44" DisplayMethod="unsigned integer"/>
      <Element Offset="3164" Vartype="String" Bytesize="5" OffsetHex="00000C5C" DisplayMethod="unsigned integer"/>
      <Element Offset="3169" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000C61" DisplayMethod="unsigned integer"/>
      <Element Offset="3172" Vartype="Float" Bytesize="4" RLECount="11" OffsetHex="00000C64" DisplayMethod="unsigned integer"/>
      <Element Offset="3216" Vartype="String" Bytesize="4" OffsetHex="00000C90" DisplayMethod="unsigned integer"/>
      <Element Offset="3220" Vartype="Float" Bytesize="4" OffsetHex="00000C94" DisplayMethod="unsigned integer"/>
      <Element Offset="3224" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000C98" DisplayMethod="unsigned integer"/>
      <Element Offset="3228" Vartype="Double" Bytesize="8" OffsetHex="00000C9C" DisplayMethod="unsigned integer"/>
      <Element Offset="3236" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000CA4" DisplayMethod="unsigned integer"/>
      <Element Offset="3244" Vartype="Float" Bytesize="4" RLECount="19" OffsetHex="00000CAC" DisplayMethod="unsigned integer"/>
      <Element Offset="3320" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000CF8" DisplayMethod="hexadecimal"/>
      <Element Offset="3324" Vartype="Double" Bytesize="8" OffsetHex="00000CFC" DisplayMethod="unsigned integer"/>
      <Element Offset="3332" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000D04" DisplayMethod="unsigned integer"/>
      <Element Offset="3340" Vartype="Double" Bytesize="8" OffsetHex="00000D0C" DisplayMethod="unsigned integer"/>
      <Element Offset="3348" Vartype="Float" Bytesize="4" OffsetHex="00000D14" DisplayMethod="unsigned integer"/>
      <Element Offset="3352" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D18" DisplayMethod="hexadecimal"/>
      <Element Offset="3356" Vartype="Double" Bytesize="8" OffsetHex="00000D1C" DisplayMethod="unsigned integer"/>
      <Element Offset="3364" Vartype="Float" Bytesize="4" RLECount="5" OffsetHex="00000D24" DisplayMethod="unsigned integer"/>
      <Element Offset="3384" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D38" DisplayMethod="hexadecimal"/>
      <Element Offset="3388" Vartype="Double" Bytesize="8" OffsetHex="00000D3C" DisplayMethod="unsigned integer"/>
      <Element Offset="3396" Vartype="Float" Bytesize="4" OffsetHex="00000D44" DisplayMethod="unsigned integer"/>
      <Element Offset="3400" Vartype="Double" Bytesize="8" OffsetHex="00000D48" DisplayMethod="unsigned integer"/>
      <Element Offset="3408" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000D50" DisplayMethod="unsigned integer"/>
      <Element Offset="3416" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D58" DisplayMethod="unsigned integer"/>
      <Element Offset="3420" Vartype="Double" Bytesize="8" OffsetHex="00000D5C" DisplayMethod="unsigned integer"/>
      <Element Offset="3428" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D64" DisplayMethod="unsigned integer"/>
      <Element Offset="3432" Vartype="Double" Bytesize="8" OffsetHex="00000D68" DisplayMethod="unsigned integer"/>
      <Element Offset="3440" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000D70" DisplayMethod="unsigned integer"/>
      <Element Offset="3448" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D78" DisplayMethod="hexadecimal"/>
      <Element Offset="3452" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000D7C" DisplayMethod="unsigned integer"/>
      <Element Offset="3460" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D84" DisplayMethod="unsigned integer"/>
      <Element Offset="3464" Vartype="Double" Bytesize="8" OffsetHex="00000D88" DisplayMethod="unsigned integer"/>
      <Element Offset="3472" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000D90" DisplayMethod="unsigned integer"/>
      <Element Offset="3480" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D98" DisplayMethod="hexadecimal"/>
      <Element Offset="3484" Vartype="Double" Bytesize="8" OffsetHex="00000D9C" DisplayMethod="unsigned integer"/>
      <Element Offset="3492" Vartype="Float" Bytesize="4" RLECount="5" OffsetHex="00000DA4" DisplayMethod="unsigned integer"/>
      <Element Offset="3512" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DB8" DisplayMethod="unsigned integer"/>
      <Element Offset="3516" Vartype="Double" Bytesize="8" OffsetHex="00000DBC" DisplayMethod="unsigned integer"/>
      <Element Offset="3524" Vartype="Float" Bytesize="4" RLECount="5" OffsetHex="00000DC4" DisplayMethod="unsigned integer"/>
      <Element Offset="3544" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DD8" DisplayMethod="hexadecimal"/>
      <Element Offset="3548" Vartype="Double" Bytesize="8" OffsetHex="00000DDC" DisplayMethod="unsigned integer"/>
      <Element Offset="3556" Vartype="String" Bytesize="5" OffsetHex="00000DE4" DisplayMethod="unsigned integer"/>
      <Element Offset="3561" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000DE9" DisplayMethod="unsigned integer"/>
      <Element Offset="3564" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000DEC" DisplayMethod="hexadecimal"/>
      <Element Offset="3576" Vartype="String" Bytesize="4" OffsetHex="00000DF8" DisplayMethod="unsigned integer"/>
      <Element Offset="3580" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DFC" DisplayMethod="hexadecimal"/>
      <Element Offset="3584" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000E00" DisplayMethod="unsigned integer"/>
      <Element Offset="3596" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E0C" DisplayMethod="hexadecimal"/>
      <Element Offset="3600" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E10" DisplayMethod="unsigned integer"/>
      <Element Offset="3604" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000E14" DisplayMethod="unsigned integer"/>
      <Element Offset="3608" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000E18" DisplayMethod="unsigned integer"/>
      <Element Offset="3616" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000E20" DisplayMethod="unsigned integer"/>
      <Element Offset="3624" Vartype="Double" Bytesize="8" OffsetHex="00000E28" DisplayMethod="unsigned integer"/>
      <Element Offset="3632" Vartype="Float" Bytesize="4" RLECount="5" OffsetHex="00000E30" DisplayMethod="unsigned integer"/>
      <Element Offset="3652" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000E44" DisplayMethod="unsigned integer"/>
      <Element Offset="3668" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E54" DisplayMethod="hexadecimal"/>
      <Element Offset="3672" Vartype="Float" Bytesize="4" RLECount="4" OffsetHex="00000E58" DisplayMethod="unsigned integer"/>
      <Element Offset="3688" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000E68" DisplayMethod="unsigned integer"/>
      <Element Offset="3696" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E70" DisplayMethod="hexadecimal"/>
      <Element Offset="3700" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E74" DisplayMethod="unsigned integer"/>
      <Element Offset="3704" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000E78" DisplayMethod="hexadecimal"/>
      <Element Offset="3712" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000E80" DisplayMethod="unsigned integer"/>
      <Element Offset="3720" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E88" DisplayMethod="hexadecimal"/>
      <Element Offset="3724" Vartype="4 Bytes" Bytesize="4" RLECount="18" OffsetHex="00000E8C" DisplayMethod="unsigned integer"/>
      <Element Offset="3796" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000ED4" DisplayMethod="hexadecimal"/>
      <Element Offset="3804" Vartype="Double" Bytesize="8" RLECount="2" OffsetHex="00000EDC" DisplayMethod="unsigned integer"/>
      <Element Offset="3820" Vartype="Float" Bytesize="4" OffsetHex="00000EEC" DisplayMethod="unsigned integer"/>
      <Element Offset="3824" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000EF0" DisplayMethod="unsigned integer"/>
      <Element Offset="3828" Vartype="Double" Bytesize="8" OffsetHex="00000EF4" DisplayMethod="unsigned integer"/>
      <Element Offset="3836" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000EFC" DisplayMethod="unsigned integer"/>
      <Element Offset="3844" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000F04" DisplayMethod="hexadecimal"/>
      <Element Offset="3852" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000F0C" DisplayMethod="unsigned integer"/>
      <Element Offset="3900" Vartype="Double" Bytesize="8" OffsetHex="00000F3C" DisplayMethod="unsigned integer"/>
      <Element Offset="3908" Vartype="Float" Bytesize="4" RLECount="23" OffsetHex="00000F44" DisplayMethod="unsigned integer"/>
      <Element Offset="4000" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000FA0" DisplayMethod="hexadecimal"/>
      <Element Offset="4020" Vartype="4 Bytes" Bytesize="4" RLECount="19" OffsetHex="00000FB4" DisplayMethod="unsigned integer"/>
    </Elements>
  </Structure>
</Structures>