
<Structures>
  <Structure Name="PlayerController" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000000" DisplayMethod="hexadecimal"/>
      <Element Offset="4" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000004" DisplayMethod="unsigned integer"/>
      <Element Offset="16" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000010" Description="playerHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="20" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000014" Description="actions (bitfield)" DisplayMethod="hexadecimal"/>
      <Element Offset="24" Vartype="Float" Bytesize="4" OffsetHex="00000018" DisplayMethod="unsigned integer"/>
      <Element Offset="28" Vartype="Float" Bytesize="4" OffsetHex="0000001C" Description="yaw" DisplayMethod="unsigned integer"/>
      <Element Offset="32" Vartype="Float" Bytesize="4" OffsetHex="00000020" Description="pitch" DisplayMethod="unsigned integer"/>
      <Element Offset="36" Vartype="Float" Bytesize="4" OffsetHex="00000024" Description="walkY" DisplayMethod="unsigned integer"/>
      <Element Offset="40" Vartype="Float" Bytesize="4" OffsetHex="00000028" Description="walkX" DisplayMethod="unsigned integer"/>
      <Element Offset="44" Vartype="Float" Bytesize="4" OffsetHex="0000002C" Description="gunTrigger" DisplayMethod="unsigned integer"/>
      <Element Offset="48" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000030" DisplayMethod="unsigned integer"/>
      <Element Offset="52" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000034" DisplayMethod="hexadecimal"/>
      <Element Offset="56" Vartype="Float" Bytesize="4" OffsetHex="00000038" Description="targetIndicator" DisplayMethod="unsigned integer"/>
      <Element Offset="60" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="0000003C" DisplayMethod="unsigned integer"/>
      <Element Offset="80" Vartype="Double" Bytesize="8" OffsetHex="00000050" DisplayMethod="unsigned integer"/>
      <Element Offset="88" Vartype="Float" Bytesize="4" OffsetHex="00000058" DisplayMethod="unsigned integer"/>
      <Element Offset="92" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="0000005C" DisplayMethod="hexadecimal"/>
      <Element Offset="100" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000064" DisplayMethod="unsigned integer"/>
      <Element Offset="140" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000008C" DisplayMethod="hexadecimal"/>
      <Element Offset="144" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000090" DisplayMethod="unsigned integer"/>
      <Element Offset="168" Vartype="Double" Bytesize="8" OffsetHex="000000A8" DisplayMethod="unsigned integer"/>
      <Element Offset="176" Vartype="Float" Bytesize="4" OffsetHex="000000B0" DisplayMethod="unsigned integer"/>
      <Element Offset="180" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="000000B4" DisplayMethod="unsigned integer"/>
      <Element Offset="228" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000E4" DisplayMethod="hexadecimal"/>
      <Element Offset="232" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000000E8" DisplayMethod="unsigned integer"/>
      <Element Offset="256" Vartype="Double" Bytesize="8" OffsetHex="00000100" DisplayMethod="unsigned integer"/>
      <Element Offset="264" Vartype="Float" Bytesize="4" OffsetHex="00000108" DisplayMethod="unsigned integer"/>
      <Element Offset="268" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="0000010C" DisplayMethod="unsigned integer"/>
      <Element Offset="316" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000013C" DisplayMethod="hexadecimal"/>
      <Element Offset="320" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000140" DisplayMethod="unsigned integer"/>
      <Element Offset="344" Vartype="Double" Bytesize="8" OffsetHex="00000158" DisplayMethod="unsigned integer"/>
      <Element Offset="352" Vartype="Float" Bytesize="4" OffsetHex="00000160" DisplayMethod="unsigned integer"/>
      <Element Offset="356" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000164" DisplayMethod="unsigned integer"/>
      <Element Offset="368" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000170" DisplayMethod="hexadecimal"/>
      <Element Offset="372" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000174" DisplayMethod="unsigned integer"/>
      <Element Offset="376" Vartype="Double" Bytesize="8" OffsetHex="00000178" DisplayMethod="unsigned integer"/>
      <Element Offset="384" Vartype="Float" Bytesize="4" RLECount="3" OffsetHex="00000180" DisplayMethod="unsigned integer"/>
      <Element Offset="396" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="0000018C" DisplayMethod="unsigned integer"/>
      <Element Offset="404" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000194" DisplayMethod="hexadecimal"/>
      <Element Offset="408" Vartype="Float" Bytesize="4" OffsetHex="00000198" DisplayMethod="unsigned integer"/>
      <Element Offset="412" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="0000019C" DisplayMethod="unsigned integer"/>
      <Element Offset="420" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001A4" Description="targetHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="424" Vartype="4 Bytes" Bytesize="4" RLECount="9" OffsetHex="000001A8" DisplayMethod="unsigned integer"/>
      <Element Offset="460" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001CC" DisplayMethod="hexadecimal"/>
      <Element Offset="464" Vartype="4 Bytes" Bytesize="4" RLECount="13" OffsetHex="000001D0" DisplayMethod="unsigned integer"/>
      <Element Offset="516" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000204" DisplayMethod="hexadecimal"/>
      <Element Offset="520" Vartype="4 Bytes" Bytesize="4" RLECount="13" OffsetHex="00000208" DisplayMethod="unsigned integer"/>
      <Element Offset="572" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000023C" DisplayMethod="hexadecimal"/>
      <Element Offset="576" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000240" DisplayMethod="unsigned integer"/>
      <Element Offset="596" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000254" DisplayMethod="hexadecimal"/>
      <Element Offset="604" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000025C" DisplayMethod="unsigned integer"/>
      <Element Offset="616" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000268" DisplayMethod="hexadecimal"/>
      <Element Offset="620" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000026C" DisplayMethod="unsigned integer"/>
      <Element Offset="632" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000278" DisplayMethod="hexadecimal"/>
      <Element Offset="636" Vartype="4 Bytes" Bytesize="4" RLECount="36" OffsetHex="0000027C" DisplayMethod="unsigned integer"/>
      <Element Offset="780" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000030C" DisplayMethod="hexadecimal"/>
      <Element Offset="784" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000310" DisplayMethod="unsigned integer"/>
      <Element Offset="796" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000031C" DisplayMethod="hexadecimal"/>
      <Element Offset="800" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="00000320" DisplayMethod="unsigned integer"/>
      <Element Offset="828" Vartype="String" Bytesize="9" OffsetHex="0000033C" DisplayMethod="unsigned integer"/>
      <Element Offset="837" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000345" DisplayMethod="unsigned integer"/>
      <Element Offset="840" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000348" DisplayMethod="unsigned integer"/>
      <Element Offset="856" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000358" DisplayMethod="hexadecimal"/>
      <Element Offset="864" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000360" DisplayMethod="unsigned integer"/>
      <Element Offset="868" Vartype="String" Bytesize="5" OffsetHex="00000364" DisplayMethod="unsigned integer"/>
      <Element Offset="873" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000369" DisplayMethod="unsigned integer"/>
      <Element Offset="876" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000036C" DisplayMethod="hexadecimal"/>
      <Element Offset="880" Vartype="4 Bytes" Bytesize="4" RLECount="804" OffsetHex="00000370" DisplayMethod="unsigned integer"/>
    </Elements>
  </Structure>
</Structures>