#define _STR(x) #x
#define STR(x) _STR(x)
#define CONCAT(x, y) x##y
#define WIDE(x) CONCAT(L,x)

#define SUPERHOTMCC_VERSION_MAJOR 0
#define SUPERHOTMCC_VERSION_MINOR 04
#define SUPERHOTMCC_VERSION_PATCH 1
#define SUPERHOTMCC_VERSION_BUILD 0

#define SUPERHOTMCC_VERSION_BIN SUPERHOTMCC_VERSION_MAJOR,SUPERHOTMCC_VERSION_MINOR,SUPERHOTMCC_VERSION_PATCH,SUPERHOTMCC_VERSION_BUILD

// #define __SUPERHOTMCC_VERSION_STRING SUPERHOTMCC_VERSION_MAJOR.SUPERHOTMCC_VERSION_MINOR.SUPERHOTMCC_VERSION_PATCH.SUPERHOTMCC_VERSION_BUILD
#define __SUPERHOTMCC_VERSION_STRING SUPERHOTMCC_VERSION_MAJOR.SUPERHOTMCC_VERSION_MINOR.SUPERHOTMCC_VERSION_PATCH
#define SUPERHOTMCC_VERSION_STRING STR(__SUPERHOTMCC_VERSION_STRING)
#define SUPERHOTMCC_VERSION_WSTRING WIDE(SUPERHOTMCC_VERSION_STRING)
